
services:
  ytdl-server:
    image: ghcr.io/nhas/ytdlp-api:latest
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - downloads:/downloads
      - data:/data
      - ./config.json:/app/config.json:ro
 
volumes:
  downloads:
  data: